---
# parameters to select positive elements group
positive_event:
  # group name
  name: passed
  # filters for events
  filters:
    # filters for events that are in full_match
    lostUser:
      full_match:
        - facebook_login_pressed
        - signup_pressed
        - login_pressed
    buyPremium:
      full_match:
        - premium_bought

negative_event:
  # group name
  name: lost