runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:flaskApp

manual_scaling:
  instances: 1

runtime_config:
  python_version: 2

beta_settings:
  cloud_sql_instances: "my-team-project-217908:europe-west1:retention"